#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

FROM jekyll/jekyll:stable

# Configure apt and install packages

# Install eslint globally
RUN npm install -g eslint \
    && gem install jekyll-seo-tag